### PR TITLE
Updated Ice Shard

### PR DESCRIPTION
**Pull request by CaraAra**
+ Preset.toml follows new conventions
+ Custom.css variables updated to reflect current application

### CODE REVIEW

**Comment by Rexogamer** [comment]
This will likely need updating

**Comment by user51112** [comment]
I'm sure it has for a good while now, I should be free to run through it soon, thank you for the reminder

**Comment by insertish** [comment]
You should be able to switch to just matching concrete class names now.

**Comment by user51112** [comment]
Based!

**Pull request closed without merging**
