### PR TITLE
Cats

### PR DESCRIPTION
**Pull request by LazyCat2**
There are some screenshots
Settings
Context menu
Profile
Messages

### CODE REVIEW

**Comment by Ka4ok52** [comment]
bruh

**Comment by Rexogamer** [comment]
Quick question - where did you get these images?

**Comment by LazyCat2** [comment]
> Quick question - where did you get these images?

I found this image [here](https://lv.sputniknews.ru/20200808/koshki-14171634.html), not sure if there is copyright issue, if needed I'll change that photo to other, that shouldn't have that issue

**Comment by Rexogamer** [comment]
I think it'd be best to use something like one of [these](https://commons.wikimedia.org/w/index.php?search=Cat&title=Special:MediaSearch&type=image&haslicense=unrestricted)?

**Review by Rexogamer — APPROVED** [review]

**Review by Rexogamer — APPROVED** [review]

**Pull request merged**
