### PR TITLE
Add IRC chat theme

### PR DESCRIPTION
**Pull request by ERROR-404-NULL-NOT-FOUND**
Adds a pure CSS theme for emulating the look and feel of an IRC chat (or compact mode)
Credits: 
`@Davari` - original theme
`@MYT` - modifications
`@ERROR 404 NULL: NOT FOUND` - submitting theme
Screenshot 2022-01-31 15 02 25
Screenshot 2022-01-31 15 02 19

### CODE REVIEW

**Comment by VeiledProduct80** [comment]
https://user-images.githubusercontent.com/71269275/169845277-d4eb9147-64a7-49ce-9d2f-ebba5537c9fb.mp4

**Comment by janderedev** [comment]
> My god you guys are unhelpful

**Comment by DoruDoLasu** [comment]
theme

**Comment by Rexogamer** [comment]
I'm certain we were planning to add a native compact theme? Not sure, although that by itself is not a blocker against merging this PR

**Comment by FanMclaine** [comment]
> Clusterfuck

nek

**Comment by SingleSlice** [comment]
sample_cbb4e2464e986e63294f9502257220402f98d3a0

**Comment by janderedev** [comment]
shitposting_inc-x9d3zk

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Average revolt conversation

**Comment by DellOptiplex9020** [comment]
amoung pequeno

**Pull request merged**
