### PR TITLE
add amethyst theme

### PR DESCRIPTION
**Pull request by itzTheMeow**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

Adds amethyst theme based on [Amethyst BetterDiscord](https://github.com/spinfish/amethyst).

### CODE REVIEW

**Comment by Zixenar** [comment]
peepee

**Comment by Rexogamer** [comment]
A screenshot would be useful (albeit not mandatory) - although if it looks similar to the BD theme, I'd say it's quite nice indeed :3

**Comment by itzTheMeow** [comment]
image

**Comment by itzTheMeow** [comment]
makes embeds and the hover toolbar not the same color as the background
image

**Comment by kevadesu** [comment]
woah - looks awesome

**Review by Rexogamer — APPROVED** [review]

**Pull request merged**
